on:
  push:
    branches:
      - main

env:
  LAMBDA_FUNCTION: "hello"
  AWS_REGION: "ap-southeast-1"

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}
    - name: Install requirements
      run: |
        pip install --no-binary :all: --no-compile --target src/lib/ -r requirements/app.txt
    - name: Create package
      run: |
        cd src && zip -r ../package.zip . -x "*.py[co]" -x "*__pycache__*" -x "*.egg-info*" -x "*.dist-info*" && cd ..
    - name: Upload package
      run: |
        aws lambda update-function-code --function-name ${{ env.LAMBDA_FUNCTION }} --zip-file fileb://package.zip
      